<?php
/**
 * PKCE and the pending-handshake store (M8.1, M8.3).
 *
 * @package Optionia
 */

declare( strict_types=1 );

namespace Optionia\Tests\Unit;

use Optionia\Connection\Handshake;
use Optionia\Support\Keys;
use PHPUnit\Framework\TestCase;

/**
 * PKCE generation and the pending-handshake store.
 *
 * @covers \Optionia\Connection\Handshake
 */
final class HandshakeTest extends TestCase {

	/**
	 * Reset the in-memory option store between tests.
	 */
	protected function setUp(): void {
		$GLOBALS['optionia_test_options'] = array();
	}

	/**
	 * **The cross-language contract the whole handshake turns on.**
	 *
	 * The cloud computes `createHash('sha256').update(v).digest('base64url')`
	 * and compares it to what this produces. These vectors were generated by
	 * that Node implementation and pasted here: if PHP's base64url ever differs
	 * — padding, alphabet, anything — every exchange fails with an
	 * indistinguishable `TOKEN_INVALID` and no diagnostic on either side.
	 */
	public function test_pkce_challenge_matches_the_cloud_byte_for_byte(): void {
		$this->assertSame(
			'R-yFp3ykg184xTSr9BXHiHtbqWZXIG_H4B3K5EWSDzM',
			Handshake::pkce_challenge( 'test-verifier-value' )
		);
	}

	/** Exactly one SHA-256 digest in base64url, which the cloud stores as CHAR(43). */
	public function test_challenge_is_43_characters(): void {
		$this->assertSame( 43, strlen( Handshake::pkce_challenge( 'anything at all' ) ) );
	}

	/** Base64url, never base64: `+/=` would need escaping in a URL. */
	public function test_challenge_is_url_safe(): void {
		for ( $i = 0; $i < 50; $i++ ) {
			$challenge = Handshake::pkce_challenge( 'verifier-' . $i );

			$this->assertMatchesRegularExpression( '/^[A-Za-z0-9_-]+$/', $challenge );
		}
	}

	/** A different verifier is a different challenge — the point of S256. */
	public function test_a_different_verifier_gives_a_different_challenge(): void {
		$this->assertNotSame(
			Handshake::pkce_challenge( 'one' ),
			Handshake::pkce_challenge( 'two' )
		);
	}

	public function test_no_pending_handshake_by_default(): void {
		$this->assertNull( Handshake::pending() );
	}

	public function test_reads_back_a_stored_handshake(): void {
		$GLOBALS['optionia_test_options'][ Keys::OPTION_HANDSHAKE ] = array(
			'state'    => 'a-state',
			'verifier' => 'a-verifier',
			'expires'  => time() + 60,
		);

		$pending = Handshake::pending();

		$this->assertIsArray( $pending );
		$this->assertSame( 'a-state', $pending['state'] );
		$this->assertSame( 'a-verifier', $pending['verifier'] );
	}

	/**
	 * An expired handshake is gone, and **deleted on sight**.
	 *
	 * The stored value is the PKCE verifier — the secret that stops an
	 * intercepted code being redeemed by whoever intercepted it. Leaving a dead
	 * one on disk keeps a secret alive for nothing.
	 */
	public function test_an_expired_handshake_is_discarded(): void {
		$GLOBALS['optionia_test_options'][ Keys::OPTION_HANDSHAKE ] = array(
			'state'    => 'a-state',
			'verifier' => 'a-verifier',
			'expires'  => time() - 1,
		);

		$this->assertNull( Handshake::pending() );
		$this->assertArrayNotHasKey(
			Keys::OPTION_HANDSHAKE,
			$GLOBALS['optionia_test_options']
		);
	}

	/** A malformed record is not a usable handshake. */
	public function test_a_handshake_missing_its_verifier_is_not_pending(): void {
		$GLOBALS['optionia_test_options'][ Keys::OPTION_HANDSHAKE ] = array(
			'state'   => 'a-state',
			'expires' => time() + 60,
		);

		$this->assertNull( Handshake::pending() );
	}

	public function test_forget_removes_the_handshake(): void {
		$GLOBALS['optionia_test_options'][ Keys::OPTION_HANDSHAKE ] = array(
			'state'    => 's',
			'verifier' => 'v',
			'expires'  => time() + 60,
		);

		Handshake::forget();

		$this->assertNull( Handshake::pending() );
	}
}
