import type { INestApplication } from '@nestjs/common';
/* ⚠️ `* as`, not a default import — the same esModuleInterop gap as `stripe`. */
import * as request from 'supertest';
import { DataSource } from 'typeorm';
import { v7 as uuidv7 } from 'uuid';

/* 🔴 See BillingModule: a default import of `stripe` is `undefined` at runtime. */
import Stripe = require('stripe');

import { SubscriptionStatus } from '../src/common/database/enums';
import { Invoice } from '../src/billing/entities/invoice.entity';
import { Plan } from '../src/plans/entities/plan.entity';
import { Subscription } from '../src/subscriptions/entities/subscription.entity';
import { Tenant } from '../src/tenants/entities/tenant.entity';
import { bootstrapTestApp } from './harness';

/**
 * The webhook endpoint, against real signatures and a real unique index (M22.C2/C3).
 *
 * ## Why this suite exists rather than more unit tests
 *
 * 🔴 **Three of the claims C2 makes are untestable in isolation.** That the raw
 * bytes survive the global JSON parser is a property of how the application is
 * built; that a redelivery is rejected exactly once is a property of a MySQL
 * unique index; and that a real Stripe signature verifies is a property of
 * crypto this project does not own. Unit tests with a stubbed provider would
 * pass on an app that preserves no raw body at all.
 *
 * ⚠️ **The signatures here are genuine**, generated by Stripe's own
 * `generateTestHeaderString` and verified by `constructEvent` inside the
 * adapter. Nothing about verification is mocked — only the account is absent.
 */
describe('Billing webhook (e2e)', () => {
  const SECRET = 'whsec_test_e2e_secret';

  let app: INestApplication;
  let dataSource: DataSource;

  const run = uuidv7().slice(-8);

  beforeAll(async () => {
    /*
     * ⚠️ **Set before the app is built**, because `BillingModule`'s factory
     * reads configuration once at construction. Assigning these later would
     * leave the provider null and every test below exercising G3's guard rather
     * than the webhook.
     */
    process.env.STRIPE_SECRET_KEY = 'sk_test_e2e_fake';
    process.env.STRIPE_WEBHOOK_SECRET = SECRET;

    app = await bootstrapTestApp();
    await app.init();

    dataSource = app.get(DataSource);
  });

  afterAll(async () => {
    /* Every run's rows, not just this one's: a failing run never reaches here. */
    await dataSource.query(`DELETE FROM billing_events WHERE providerEventId LIKE 'evt_e2e_%'`);

    /* Invoices are RESTRICT on tenant, so they go before subscriptions and tenants. */
    await dataSource.query(
      `DELETE i FROM invoices i JOIN tenants t ON t.id = i.tenantId WHERE t.slug LIKE 'whook-%'`,
    );
    await dataSource.query(
      `DELETE FROM subscriptions WHERE tenantId IN (SELECT id FROM tenants WHERE slug LIKE 'whook-%')`,
    );
    await dataSource.query(`DELETE FROM tenants WHERE slug LIKE 'whook-%'`);

    delete process.env.STRIPE_SECRET_KEY;
    delete process.env.STRIPE_WEBHOOK_SECRET;

    await app.close();
  });

  let seq = 0;

  /** A Stripe event body, and the signature Stripe would send with it. */
  function signedEvent(overrides: Record<string, unknown> = {}) {
    seq += 1;

    const body = JSON.stringify({
      id: `evt_e2e_${run}_${seq}`,
      object: 'event',
      type: 'invoice.paid',
      data: { object: { id: `in_e2e_${run}_${seq}`, object: 'invoice' } },
      ...overrides,
    });

    const signature = Stripe.webhooks.generateTestHeaderString({ payload: body, secret: SECRET });

    return { body, signature, eventId: JSON.parse(body).id as string };
  }

  function post(body: string, signature: string | null) {
    const req = request(app.getHttpServer())
      .post('/v1/billing/webhook')
      .set('content-type', 'application/json');

    if (signature !== null) {
      req.set('stripe-signature', signature);
    }

    return req.send(body);
  }

  describe('a genuine event', () => {
    /**
     * 🔴 **This is the raw-body proof.** The signature is over the exact bytes
     * sent; if the global JSON parser consumed them without `rawBody: true`,
     * verification fails and this answers 400. It passing means the bytes
     * survived the parser.
     */
    it('accepts it and records the event', async () => {
      const { body, signature, eventId } = signedEvent();

      const response = await post(body, signature);

      expect(response.status).toBe(200);

      /* 📌 The global interceptor wraps every response in `{ data, meta }`.
       * Stripe reads only the status code, so the envelope is harmless — but
       * asserting the bare object would fail for a reason that has nothing to
       * do with billing. */
      expect(response.body.data).toEqual({ received: true, status: 'processed' });

      const [row] = await dataSource.query(
        `SELECT provider, type, processedAt FROM billing_events WHERE providerEventId = ?`,
        [eventId],
      );

      expect(row).toMatchObject({ provider: 'stripe', type: 'invoice.paid' });
      expect(row.processedAt).not.toBeNull();
    });

    /**
     * 🔴 **The same event twice is one row and two 200s.** The unique index
     * decides it, not a read-then-write — and answering anything but 200 would
     * have Stripe redeliver it for ever.
     */
    it('is idempotent across redelivery', async () => {
      const { body, signature, eventId } = signedEvent();

      const first = await post(body, signature);
      const second = await post(body, signature);

      expect(first.body.data).toEqual({ received: true, status: 'processed' });
      expect(second.status).toBe(200);
      expect(second.body.data).toEqual({ received: true, status: 'duplicate' });

      const [{ count }] = await dataSource.query(
        `SELECT COUNT(*) AS count FROM billing_events WHERE providerEventId = ?`,
        [eventId],
      );

      expect(Number(count)).toBe(1);
    });

    /**
     * ⚠️ **Concurrent redelivery, which is the case a `SELECT` first cannot
     * survive.** Both requests see no row, both insert, and only the database
     * can break the tie — so exactly one must win and the rest must read the
     * violation as "already handled".
     */
    it('stores one row when the same event arrives concurrently', async () => {
      const { body, signature, eventId } = signedEvent();

      const responses = await Promise.all([
        post(body, signature),
        post(body, signature),
        post(body, signature),
      ]);

      expect(responses.map((r) => r.status)).toEqual([200, 200, 200]);

      const outcomes = responses.map((r) => r.body.data.status).sort();
      expect(outcomes).toEqual(['duplicate', 'duplicate', 'processed']);

      const [{ count }] = await dataSource.query(
        `SELECT COUNT(*) AS count FROM billing_events WHERE providerEventId = ?`,
        [eventId],
      );

      expect(Number(count)).toBe(1);
    });
  });

  describe('a request that did not come from Stripe', () => {
    /**
     * 🔴 **400 and nothing written.** A forged body must not be retried — no
     * number of retries makes it genuine — and must leave no trace in a table
     * an operator reads as a record of real events.
     */
    it('rejects a body whose signature does not match it', async () => {
      const { signature } = signedEvent();
      const tampered = JSON.stringify({ id: `evt_e2e_${run}_forged`, object: 'event' });

      const response = await post(tampered, signature);

      expect(response.status).toBe(400);

      const rows = await dataSource.query(
        `SELECT id FROM billing_events WHERE providerEventId = ?`,
        [`evt_e2e_${run}_forged`],
      );

      expect(rows).toHaveLength(0);
    });

    it('rejects a request with no signature header at all', async () => {
      const { body } = signedEvent();

      expect((await post(body, null)).status).toBe(400);
    });

    it('rejects a garbage signature header', async () => {
      const { body } = signedEvent();

      expect((await post(body, 't=1,v1=deadbeef')).status).toBe(400);
    });

    /**
     * ⚠️ **A signature from the right secret over a different body is still a
     * forgery**, which is the property a shared bearer token would not have.
     */
    it('rejects a valid signature replayed onto another body', async () => {
      const first = signedEvent();
      const second = signedEvent();

      expect((await post(second.body, first.signature)).status).toBe(400);
    });
  });

  /**
   * 📌 **Unauthenticated on purpose.** Authentication is global with `@Public()`
   * opt-out, so a missing decorator would make this route answer 401 to Stripe —
   * an outage that looks like a Stripe problem. The signature is the auth.
   */
  it('needs no bearer token', async () => {
    const { body, signature } = signedEvent();

    expect((await post(body, signature)).status).toBe(200);
  });

  /**
   * C4, and the half of C3's proof that could not be written until it existed.
   *
   * 🔴 **The plan's own words were *"one invoice row and one subscription
   * transition"*** — asserted here by `COUNT(*)`, not by absence of error.
   */
  describe('subscription lifecycle', () => {
    async function tenantWithSubscription(providerSubscriptionId: string) {
      const plan = await dataSource.getRepository(Plan).findOneOrFail({
        where: { code: 'free' },
      });

      seq += 1;

      const tenant = await dataSource.getRepository(Tenant).save(
        dataSource.getRepository(Tenant).create({
          name: `Webhook ${run}-${seq}`,
          slug: `whook-${run}-${seq}`,
          planId: plan.id,
          billingCurrency: 'EUR',
        }),
      );

      const subscription = await dataSource.getRepository(Subscription).save(
        dataSource.getRepository(Subscription).create({
          tenantId: tenant.id,
          planId: plan.id,
          provider: 'stripe',
          providerSubscriptionId,
          providerCustomerId: `cus_${run}_${seq}`,
          status: SubscriptionStatus.TRIALING,
        }),
      );

      return { tenant, subscription };
    }

    function invoicePayload(subscriptionId: string, invoiceId: string) {
      return {
        id: invoiceId,
        object: 'invoice',
        status: 'paid',
        currency: 'eur',
        subtotal: 2900,
        total_taxes: [{ amount: 609 }],
        total: 3509,
        created: 1_755_216_000,
        status_transitions: { paid_at: 1_755_216_060 },
        customer_address: { country: 'de' },
        parent: { subscription_details: { subscription: subscriptionId } },
      };
    }

    it('activates a subscription from invoice.paid and stores the invoice', async () => {
      const providerSubscriptionId = `sub_${run}_${seq + 1}`;
      const { tenant, subscription } = await tenantWithSubscription(providerSubscriptionId);
      const invoiceId = `in_e2e_${run}_${seq}`;

      const { body, signature } = signedEvent({
        type: 'invoice.paid',
        data: { object: invoicePayload(providerSubscriptionId, invoiceId) },
      });

      expect((await post(body, signature)).status).toBe(200);

      const updated = await dataSource
        .getRepository(Subscription)
        .findOneByOrFail({ id: subscription.id });

      expect(updated.status).toBe(SubscriptionStatus.ACTIVE);
      expect(updated.graceEndsAt).toBeNull();

      const stored = await dataSource
        .getRepository(Invoice)
        .findOneByOrFail({ providerInvoiceId: invoiceId });

      expect(stored.tenantId).toBe(tenant.id);
      expect(stored.subscriptionId).toBe(subscription.id);
      expect(stored.subtotalMinor + stored.taxMinor).toBe(stored.totalMinor);
      expect(stored.taxCountry).toBe('DE');
    });

    /**
     * 🔴 **C3's stated proof, now provable — and my first version did not prove
     * it.** Posting the identical event twice is rejected by
     * `uq_billing_events_provider_event` before the invoice code runs at all, so
     * it re-tested the webhook's idempotency and left the invoice upsert
     * untouched: a mutation turning that upsert into a plain insert **survived**.
     *
     * ⚠️ **Two DIFFERENT events about the SAME invoice is the real case** —
     * Stripe sends `invoice.paid` and then corrections or related events
     * carrying the same invoice — and only `uq_invoices_provider_invoice` plus
     * the upsert stop that becoming two rows and a doubled quarter of tax.
     */
    it('keeps one invoice row when two events carry the same invoice', async () => {
      const providerSubscriptionId = `sub_${run}_${seq + 1}`;
      await tenantWithSubscription(providerSubscriptionId);
      const invoiceId = `in_e2e_${run}_${seq}_dup`;

      const first = signedEvent({
        type: 'invoice.paid',
        data: { object: invoicePayload(providerSubscriptionId, invoiceId) },
      });
      expect((await post(first.body, first.signature)).status).toBe(200);

      /* A distinct event id, so the webhook layer lets it through to the handler. */
      const second = signedEvent({
        type: 'invoice.paid',
        data: { object: invoicePayload(providerSubscriptionId, invoiceId) },
      });
      expect(second.eventId).not.toBe(first.eventId);
      expect((await post(second.body, second.signature)).status).toBe(200);

      const [{ count }] = await dataSource.query(
        `SELECT COUNT(*) AS count FROM invoices WHERE providerInvoiceId = ?`,
        [invoiceId],
      );

      expect(Number(count)).toBe(1);
    });

    /**
     * ⚠️ **ADR-116: a failed payment starts a 14-day clock, it does not
     * suspend.** The storefront never goes dark.
     */
    it('starts the grace clock on invoice.payment_failed', async () => {
      const providerSubscriptionId = `sub_${run}_${seq + 1}`;
      const { subscription } = await tenantWithSubscription(providerSubscriptionId);

      const { body, signature } = signedEvent({
        type: 'invoice.payment_failed',
        data: {
          object: {
            id: `in_e2e_${run}_${seq}_failed`,
            object: 'invoice',
            status: 'open',
            parent: { subscription_details: { subscription: providerSubscriptionId } },
          },
        },
      });

      expect((await post(body, signature)).status).toBe(200);

      const updated = await dataSource
        .getRepository(Subscription)
        .findOneByOrFail({ id: subscription.id });

      expect(updated.status).toBe(SubscriptionStatus.PAST_DUE);
      expect(updated.graceEndsAt).not.toBeNull();

      const days = (updated.graceEndsAt!.getTime() - Date.now()) / 86_400_000;
      expect(days).toBeGreaterThan(13.9);
      expect(days).toBeLessThan(14.1);
    });

    /** 📌 An event no handler claims is still recorded, and still answers 200. */
    it('records an unhandled event type without failing', async () => {
      const { body, signature, eventId } = signedEvent({
        type: 'customer.discount.created',
        data: { object: { id: 'di_1' } },
      });

      expect((await post(body, signature)).status).toBe(200);

      const [row] = await dataSource.query(
        `SELECT processedAt, error FROM billing_events WHERE providerEventId = ?`,
        [eventId],
      );

      expect(row.processedAt).not.toBeNull();
      expect(row.error).toBeNull();
    });
  });
});
