import type { INestApplication } from '@nestjs/common';
import { ConfigDocumentBuilder } from '../src/option-sets/serialization/config-document';
/* ⚠️ `* as`, not a default import — the same esModuleInterop gap as `stripe`. */
import * as request from 'supertest';
import { DataSource } from 'typeorm';
import { v7 as uuidv7 } from 'uuid';

/* 🔴 See BillingModule: a default import of `stripe` is `undefined` at runtime. */
import Stripe = require('stripe');

import { SubscriptionStatus } from '../src/common/database/enums';
import { Invoice } from '../src/billing/entities/invoice.entity';
import { Plan } from '../src/plans/entities/plan.entity';
import { Subscription } from '../src/subscriptions/entities/subscription.entity';
import { Tenant } from '../src/tenants/entities/tenant.entity';
import { BillingEventRetryService } from '../src/billing/billing-event-retry.service';
import { bootstrapTestApp } from './harness';

/**
 * The webhook endpoint, against real signatures and a real unique index (M22.C2/C3).
 *
 * ## Why this suite exists rather than more unit tests
 *
 * 🔴 **Three of the claims C2 makes are untestable in isolation.** That the raw
 * bytes survive the global JSON parser is a property of how the application is
 * built; that a redelivery is rejected exactly once is a property of a MySQL
 * unique index; and that a real Stripe signature verifies is a property of
 * crypto this project does not own. Unit tests with a stubbed provider would
 * pass on an app that preserves no raw body at all.
 *
 * ⚠️ **The signatures here are genuine**, generated by Stripe's own
 * `generateTestHeaderString` and verified by `constructEvent` inside the
 * adapter. Nothing about verification is mocked — only the account is absent.
 */
/** Put a variable back exactly as it was, absent included. */
function restore(key: string, value: string | undefined): void {
  if (value === undefined) {
    delete process.env[key];
  } else {
    process.env[key] = value;
  }
}

describe('Billing webhook (e2e)', () => {
  const SECRET = 'whsec_test_e2e_secret';

  let app: INestApplication;
  let dataSource: DataSource;

  const run = uuidv7().slice(-8);

  /*
   * 🔴 **Captured so teardown RESTORES rather than deletes (K4).** An earlier
   * version deleted both keys in `afterAll`, which with real keys now in `.env`
   * would leave any later suite constructing a billing provider seeing none.
   * Harmless today — no later suite does — but it is the same aggressor pattern
   * already fixed once in `checkout.service.spec.ts`, and a suite that destroys
   * shared global state is an aggressor even when its own assertions are right.
   */
  const savedKeys = {
    secret: process.env.STRIPE_SECRET_KEY,
    webhook: process.env.STRIPE_WEBHOOK_SECRET,
  };

  beforeAll(async () => {
    /*
     * ⚠️ **Set before the app is built**, because `BillingModule`'s factory
     * reads configuration once at construction. Assigning these later would
     * leave the provider null and every test below exercising G3's guard rather
     * than the webhook.
     *
     * 📌 A fake secret on purpose: nothing here calls the provider's API, and a
     * real key in a test run is a real account one bug away from being touched.
     */
    process.env.STRIPE_SECRET_KEY = 'sk_test_e2e_fake';
    process.env.STRIPE_WEBHOOK_SECRET = SECRET;

    app = await bootstrapTestApp();
    await app.init();

    dataSource = app.get(DataSource);
  });

  afterAll(async () => {
    /* Every run's rows, not just this one's: a failing run never reaches here. */
    await dataSource.query(`DELETE FROM billing_events WHERE providerEventId LIKE 'evt_e2e_%'`);

    /*
     * ⚠️ **The lifecycle test's own fixtures, removed before the tenants.**
     * `option_sets` and `stores` are RESTRICT on `tenantId`, so leaving them
     * makes the tenant delete below fail — and the suite reports a teardown
     * error after every test has passed, which reads as a product failure.
     */
    await dataSource.query(
      `DELETE FROM option_sets WHERE tenantId IN
         (SELECT id FROM tenants WHERE slug LIKE 'whook-%')`,
    );

    await dataSource.query(
      `DELETE FROM stores WHERE tenantId IN
         (SELECT id FROM tenants WHERE slug LIKE 'whook-%')`,
    );

    /* Invoices are RESTRICT on tenant, so they go before subscriptions and tenants. */
    await dataSource.query(
      `DELETE i FROM invoices i JOIN tenants t ON t.id = i.tenantId WHERE t.slug LIKE 'whook-%'`,
    );
    await dataSource.query(
      `DELETE FROM subscriptions WHERE tenantId IN (SELECT id FROM tenants WHERE slug LIKE 'whook-%')`,
    );
    await dataSource.query(`DELETE FROM tenants WHERE slug LIKE 'whook-%'`);

    restore('STRIPE_SECRET_KEY', savedKeys.secret);
    restore('STRIPE_WEBHOOK_SECRET', savedKeys.webhook);

    await app.close();
  });

  let seq = 0;

  /** A Stripe event body, and the signature Stripe would send with it. */
  function signedEvent(overrides: Record<string, unknown> = {}) {
    seq += 1;

    const body = JSON.stringify({
      id: `evt_e2e_${run}_${seq}`,
      object: 'event',
      type: 'invoice.paid',
      data: { object: { id: `in_e2e_${run}_${seq}`, object: 'invoice' } },
      ...overrides,
    });

    const signature = Stripe.webhooks.generateTestHeaderString({ payload: body, secret: SECRET });

    return { body, signature, eventId: JSON.parse(body).id as string };
  }

  function post(body: string, signature: string | null) {
    const req = request(app.getHttpServer())
      .post('/v1/billing/webhook')
      .set('content-type', 'application/json');

    if (signature !== null) {
      req.set('stripe-signature', signature);
    }

    return req.send(body);
  }

  describe('a genuine event', () => {
    /**
     * 🔴 **This is the raw-body proof.** The signature is over the exact bytes
     * sent; if the global JSON parser consumed them without `rawBody: true`,
     * verification fails and this answers 400. It passing means the bytes
     * survived the parser.
     */
    it('accepts it and records the event', async () => {
      const { body, signature, eventId } = signedEvent();

      const response = await post(body, signature);

      expect(response.status).toBe(200);

      /* 📌 The global interceptor wraps every response in `{ data, meta }`.
       * Stripe reads only the status code, so the envelope is harmless — but
       * asserting the bare object would fail for a reason that has nothing to
       * do with billing. */
      expect(response.body.data).toEqual({ received: true, status: 'processed' });

      const [row] = await dataSource.query(
        `SELECT provider, type, processedAt FROM billing_events WHERE providerEventId = ?`,
        [eventId],
      );

      expect(row).toMatchObject({ provider: 'stripe', type: 'invoice.paid' });
      expect(row.processedAt).not.toBeNull();
    });

    /**
     * 🔴 **The same event twice is one row and two 200s.** The unique index
     * decides it, not a read-then-write — and answering anything but 200 would
     * have Stripe redeliver it for ever.
     */
    it('is idempotent across redelivery', async () => {
      const { body, signature, eventId } = signedEvent();

      const first = await post(body, signature);
      const second = await post(body, signature);

      expect(first.body.data).toEqual({ received: true, status: 'processed' });
      expect(second.status).toBe(200);
      expect(second.body.data).toEqual({ received: true, status: 'duplicate' });

      const [{ count }] = await dataSource.query(
        `SELECT COUNT(*) AS count FROM billing_events WHERE providerEventId = ?`,
        [eventId],
      );

      expect(Number(count)).toBe(1);
    });

    /**
     * ⚠️ **Concurrent redelivery, which is the case a `SELECT` first cannot
     * survive.** Both requests see no row, both insert, and only the database
     * can break the tie — so exactly one must win and the rest must read the
     * violation as "already handled".
     */
    it('stores one row when the same event arrives concurrently', async () => {
      const { body, signature, eventId } = signedEvent();

      const responses = await Promise.all([
        post(body, signature),
        post(body, signature),
        post(body, signature),
      ]);

      expect(responses.map((r) => r.status)).toEqual([200, 200, 200]);

      const outcomes = responses.map((r) => r.body.data.status).sort();
      expect(outcomes).toEqual(['duplicate', 'duplicate', 'processed']);

      const [{ count }] = await dataSource.query(
        `SELECT COUNT(*) AS count FROM billing_events WHERE providerEventId = ?`,
        [eventId],
      );

      expect(Number(count)).toBe(1);
    });
  });

  describe('a request that did not come from Stripe', () => {
    /**
     * 🔴 **400 and nothing written.** A forged body must not be retried — no
     * number of retries makes it genuine — and must leave no trace in a table
     * an operator reads as a record of real events.
     */
    it('rejects a body whose signature does not match it', async () => {
      const { signature } = signedEvent();
      const tampered = JSON.stringify({ id: `evt_e2e_${run}_forged`, object: 'event' });

      const response = await post(tampered, signature);

      expect(response.status).toBe(400);

      const rows = await dataSource.query(
        `SELECT id FROM billing_events WHERE providerEventId = ?`,
        [`evt_e2e_${run}_forged`],
      );

      expect(rows).toHaveLength(0);
    });

    it('rejects a request with no signature header at all', async () => {
      const { body } = signedEvent();

      expect((await post(body, null)).status).toBe(400);
    });

    it('rejects a garbage signature header', async () => {
      const { body } = signedEvent();

      expect((await post(body, 't=1,v1=deadbeef')).status).toBe(400);
    });

    /**
     * ⚠️ **A signature from the right secret over a different body is still a
     * forgery**, which is the property a shared bearer token would not have.
     */
    it('rejects a valid signature replayed onto another body', async () => {
      const first = signedEvent();
      const second = signedEvent();

      expect((await post(second.body, first.signature)).status).toBe(400);
    });
  });

  /**
   * 📌 **Unauthenticated on purpose.** Authentication is global with `@Public()`
   * opt-out, so a missing decorator would make this route answer 401 to Stripe —
   * an outage that looks like a Stripe problem. The signature is the auth.
   */
  it('needs no bearer token', async () => {
    const { body, signature } = signedEvent();

    expect((await post(body, signature)).status).toBe(200);
  });

  /**
   * C4, and the half of C3's proof that could not be written until it existed.
   *
   * 🔴 **The plan's own words were *"one invoice row and one subscription
   * transition"*** — asserted here by `COUNT(*)`, not by absence of error.
   */
  describe('subscription lifecycle', () => {
    async function tenantWithSubscription(providerSubscriptionId: string) {
      const plan = await dataSource.getRepository(Plan).findOneOrFail({
        where: { code: 'free' },
      });

      seq += 1;

      const tenant = await dataSource.getRepository(Tenant).save(
        dataSource.getRepository(Tenant).create({
          name: `Webhook ${run}-${seq}`,
          slug: `whook-${run}-${seq}`,
          planId: plan.id,
          billingCurrency: 'EUR',
        }),
      );

      const subscription = await dataSource.getRepository(Subscription).save(
        dataSource.getRepository(Subscription).create({
          tenantId: tenant.id,
          planId: plan.id,
          provider: 'stripe',
          providerSubscriptionId,
          providerCustomerId: `cus_${run}_${seq}`,
          status: SubscriptionStatus.TRIALING,
        }),
      );

      return { tenant, subscription };
    }

    function invoicePayload(subscriptionId: string, invoiceId: string) {
      return {
        id: invoiceId,
        object: 'invoice',
        status: 'paid',
        currency: 'eur',
        subtotal: 2900,
        total_taxes: [{ amount: 609 }],
        total: 3509,
        created: 1_755_216_000,
        status_transitions: { paid_at: 1_755_216_060 },
        customer_address: { country: 'de' },
        parent: { subscription_details: { subscription: subscriptionId } },
      };
    }

    it('activates a subscription from invoice.paid and stores the invoice', async () => {
      const providerSubscriptionId = `sub_${run}_${seq + 1}`;
      const { tenant, subscription } = await tenantWithSubscription(providerSubscriptionId);
      const invoiceId = `in_e2e_${run}_${seq}`;

      const { body, signature } = signedEvent({
        type: 'invoice.paid',
        data: { object: invoicePayload(providerSubscriptionId, invoiceId) },
      });

      expect((await post(body, signature)).status).toBe(200);

      const updated = await dataSource
        .getRepository(Subscription)
        .findOneByOrFail({ id: subscription.id });

      expect(updated.status).toBe(SubscriptionStatus.ACTIVE);
      expect(updated.graceEndsAt).toBeNull();

      const stored = await dataSource
        .getRepository(Invoice)
        .findOneByOrFail({ providerInvoiceId: invoiceId });

      expect(stored.tenantId).toBe(tenant.id);
      expect(stored.subscriptionId).toBe(subscription.id);
      expect(stored.subtotalMinor + stored.taxMinor).toBe(stored.totalMinor);
      expect(stored.taxCountry).toBe('DE');
    });

    /**
     * 🔴 **C3's stated proof, now provable — and my first version did not prove
     * it.** Posting the identical event twice is rejected by
     * `uq_billing_events_provider_event` before the invoice code runs at all, so
     * it re-tested the webhook's idempotency and left the invoice upsert
     * untouched: a mutation turning that upsert into a plain insert **survived**.
     *
     * ⚠️ **Two DIFFERENT events about the SAME invoice is the real case** —
     * Stripe sends `invoice.paid` and then corrections or related events
     * carrying the same invoice — and only `uq_invoices_provider_invoice` plus
     * the upsert stop that becoming two rows and a doubled quarter of tax.
     */
    it('keeps one invoice row when two events carry the same invoice', async () => {
      const providerSubscriptionId = `sub_${run}_${seq + 1}`;
      await tenantWithSubscription(providerSubscriptionId);
      const invoiceId = `in_e2e_${run}_${seq}_dup`;

      const first = signedEvent({
        type: 'invoice.paid',
        data: { object: invoicePayload(providerSubscriptionId, invoiceId) },
      });
      expect((await post(first.body, first.signature)).status).toBe(200);

      /* A distinct event id, so the webhook layer lets it through to the handler. */
      const second = signedEvent({
        type: 'invoice.paid',
        data: { object: invoicePayload(providerSubscriptionId, invoiceId) },
      });
      expect(second.eventId).not.toBe(first.eventId);
      expect((await post(second.body, second.signature)).status).toBe(200);

      const [{ count }] = await dataSource.query(
        `SELECT COUNT(*) AS count FROM invoices WHERE providerInvoiceId = ?`,
        [invoiceId],
      );

      expect(Number(count)).toBe(1);
    });

    /**
     * ⚠️ **ADR-116: a failed payment starts a 14-day clock, it does not
     * suspend.** The storefront never goes dark.
     */
    it('starts the grace clock on invoice.payment_failed', async () => {
      const providerSubscriptionId = `sub_${run}_${seq + 1}`;
      const { subscription } = await tenantWithSubscription(providerSubscriptionId);

      const { body, signature } = signedEvent({
        type: 'invoice.payment_failed',
        data: {
          object: {
            id: `in_e2e_${run}_${seq}_failed`,
            object: 'invoice',
            status: 'open',
            parent: { subscription_details: { subscription: providerSubscriptionId } },
          },
        },
      });

      expect((await post(body, signature)).status).toBe(200);

      const updated = await dataSource
        .getRepository(Subscription)
        .findOneByOrFail({ id: subscription.id });

      expect(updated.status).toBe(SubscriptionStatus.PAST_DUE);
      expect(updated.graceEndsAt).not.toBeNull();

      const days = (updated.graceEndsAt!.getTime() - Date.now()) / 86_400_000;
      expect(days).toBeGreaterThan(13.9);
      expect(days).toBeLessThan(14.1);
    });

    /** 📌 An event no handler claims is still recorded, and still answers 200. */
    it('records an unhandled event type without failing', async () => {
      const { body, signature, eventId } = signedEvent({
        type: 'customer.discount.created',
        data: { object: { id: 'di_1' } },
      });

      expect((await post(body, signature)).status).toBe(200);

      const [row] = await dataSource.query(
        `SELECT processedAt, error FROM billing_events WHERE providerEventId = ?`,
        [eventId],
      );

      expect(row.processedAt).not.toBeNull();
      expect(row.error).toBeNull();
    });
  });

  /**
   * H4 — the ordering defect, proven fixed against the real database.
   *
   * 🔴 **This was measured before it was fixed.** A probe delivered
   * `customer.subscription.updated` before the checkout event: the request
   * answered **200** and the subscription stayed `trialing`. Stripe never
   * redelivers a 200, so a merchant who had paid was left unpaid, silently.
   */
  describe('out-of-order delivery (H4)', () => {
    it('activates a subscription whose id has not been linked yet', async () => {
      const plan = await dataSource.getRepository(Plan).findOneOrFail({ where: { code: 'free' } });

      seq += 1;
      const providerCustomerId = `cus_${run}_${seq}`;
      const providerSubscriptionId = `sub_${run}_${seq}_reorder`;

      const tenant = await dataSource.getRepository(Tenant).save(
        dataSource.getRepository(Tenant).create({
          name: `Reorder ${run}-${seq}`,
          slug: `whook-${run}-${seq}`,
          planId: plan.id,
          billingCurrency: 'EUR',
        }),
      );

      /* Checkout has NOT run: the customer is known, the subscription id is not. */
      const subscription = await dataSource.getRepository(Subscription).save(
        dataSource.getRepository(Subscription).create({
          tenantId: tenant.id,
          planId: plan.id,
          provider: 'stripe',
          providerCustomerId,
          providerSubscriptionId: null,
          status: SubscriptionStatus.TRIALING,
        }),
      );

      const { body, signature } = signedEvent({
        type: 'customer.subscription.updated',
        data: {
          object: {
            id: providerSubscriptionId,
            status: 'active',
            customer: providerCustomerId,
          },
        },
      });

      expect((await post(body, signature)).status).toBe(200);

      const updated = await dataSource
        .getRepository(Subscription)
        .findOneByOrFail({ id: subscription.id });

      expect(updated.status).toBe(SubscriptionStatus.ACTIVE);

      /* ⚠️ And it adopted the id, so the checkout event that follows finds it linked. */
      expect(updated.providerSubscriptionId).toBe(providerSubscriptionId);
    });
  });

  /**
   * N1 — recovery of an event claimed by a delivery that failed.
   *
   * 🔴 **Only the real unique index can prove this.** The claim is an INSERT
   * that collides; a stubbed repository can imitate the collision but not the
   * row that survives it, and the row is the whole point.
   */
  describe('a webhook that failed midway (N1)', () => {
    it('re-runs the handler when a redelivery finds unfinished work', async () => {
      const plan = await dataSource.getRepository(Plan).findOneOrFail({ where: { code: 'free' } });

      seq += 1;
      const providerSubscriptionId = `sub_${run}_${seq}_n1`;

      const tenant = await dataSource.getRepository(Tenant).save(
        dataSource.getRepository(Tenant).create({
          name: `N1 ${run}-${seq}`,
          slug: `whook-${run}-${seq}`,
          planId: plan.id,
          billingCurrency: 'EUR',
        }),
      );

      const subscriptions = dataSource.getRepository(Subscription);
      const subscription = await subscriptions.save(
        subscriptions.create({
          tenantId: tenant.id,
          planId: plan.id,
          provider: 'stripe',
          providerSubscriptionId,
          status: SubscriptionStatus.PAST_DUE,
        }),
      );

      const { body, signature, eventId } = signedEvent({
        type: 'customer.subscription.updated',
        data: { object: { id: providerSubscriptionId, status: 'active' } },
      });

      /*
       * ⚠️ **The claim is simulated, not forced by breaking the app.** Writing
       * the row with `processedAt` null is exactly the state a failed handler
       * leaves behind, and it can be created without making the server throw —
       * which would be a far less precise test of a far larger surface.
       */
      await dataSource.query(
        `INSERT INTO billing_events (id, provider, providerEventId, type, payload, processedAt, error, createdAt, updatedAt)
         VALUES (UUID(), 'stripe', ?, 'customer.subscription.updated', '{}', NULL, 'transient failure', NOW(3), NOW(3))`,
        [eventId],
      );

      const response = await post(body, signature);

      expect(response.status).toBe(200);
      expect(response.body.data.status).toBe('processed');

      /* 🔴 The merchant is active: the work the first delivery owed is done. */
      const after = await subscriptions.findOneByOrFail({ id: subscription.id });
      expect(after.status).toBe(SubscriptionStatus.ACTIVE);

      /* ⚠️ And the row is finished, with the earlier error cleared. */
      const [row] = await dataSource.query(
        `SELECT processedAt, error FROM billing_events WHERE providerEventId = ?`,
        [eventId],
      );

      expect(row.processedAt).not.toBeNull();
      expect(row.error).toBeNull();
    });

    /**
     * 🔴 **A FINISHED event stays a no-op**, which is the guarantee the N1 fix
     * must not trade away — re-applying a completed event is the double-charge
     * the whole mechanism exists to prevent.
     */
    it('still ignores a redelivery of an event that completed', async () => {
      const plan = await dataSource.getRepository(Plan).findOneOrFail({ where: { code: 'free' } });

      seq += 1;
      const providerSubscriptionId = `sub_${run}_${seq}_done`;

      const tenant = await dataSource.getRepository(Tenant).save(
        dataSource.getRepository(Tenant).create({
          name: `N1done ${run}-${seq}`,
          slug: `whook-${run}-${seq}`,
          planId: plan.id,
          billingCurrency: 'EUR',
        }),
      );

      const subscriptions = dataSource.getRepository(Subscription);
      const subscription = await subscriptions.save(
        subscriptions.create({
          tenantId: tenant.id,
          planId: plan.id,
          provider: 'stripe',
          providerSubscriptionId,
          status: SubscriptionStatus.PAST_DUE,
        }),
      );

      const { body, signature, eventId } = signedEvent({
        type: 'customer.subscription.updated',
        data: { object: { id: providerSubscriptionId, status: 'active' } },
      });

      /* Already processed by an earlier delivery. */
      await dataSource.query(
        `INSERT INTO billing_events (id, provider, providerEventId, type, payload, processedAt, error, createdAt, updatedAt)
         VALUES (UUID(), 'stripe', ?, 'customer.subscription.updated', '{}', NOW(3), NULL, NOW(3), NOW(3))`,
        [eventId],
      );

      const response = await post(body, signature);

      expect(response.status).toBe(200);
      expect(response.body.data.status).toBe('duplicate');

      /* The handler did not run: the merchant is untouched. */
      const after = await subscriptions.findOneByOrFail({ id: subscription.id });
      expect(after.status).toBe(SubscriptionStatus.PAST_DUE);
    });
  });

  /**
   * ADR-116's dunning mail, end to end (M23.3).
   *
   * 🔴 **Every link was stubbed until now.** The lifecycle called a spy, the
   * notifier took a fake `MailService`, the contacts service took a fake
   * repository — so the query joining `tenant_members` to `users` with a
   * `revokedAt IS NULL` filter had **never run against MySQL**. That is the
   * shape of gap F103 found in the sandbox: every contract satisfied, and the
   * real thing untried.
   *
   * ⚠️ **No mail leaves this machine.** `SMTP_HOST` is empty, so `LogTransport`
   * handles it — and because that transport still returns a message id,
   * `MailService` writes an `email_deliveries` row. The row is the proof.
   */
  describe('dunning mail (ADR-116)', () => {
    afterEach(async () => {
      await dataSource.query(
        `DELETE FROM email_deliveries WHERE recipient LIKE '%@dunning.test'`,
      );
    });

    async function tenantWithOwner(which: string): Promise<{ tenantId: string; email: string }> {
      const plan = await dataSource.getRepository(Plan).findOneOrFail({ where: { code: 'free' } });

      seq += 1;
      const email = `${which}-${run}@dunning.test`;

      const tenant = await dataSource.getRepository(Tenant).save(
        dataSource.getRepository(Tenant).create({
          name: `Dunning ${run}-${seq}`,
          slug: `whook-${run}-${seq}`,
          planId: plan.id,
          billingCurrency: 'EUR',
        }),
      );

      /*
       * ⚠️ **Verified, because the contacts service excludes unverified
       * addresses** — mailing an unconfirmed address degrades deliverability
       * for every merchant who *is* reachable.
       */
      const [user] = await dataSource.query(
        `INSERT INTO users (id, email, passwordHash, name, emailVerifiedAt, createdAt, updatedAt)
         VALUES (UUID(), ?, 'x', 'Dunning Owner', NOW(3), NOW(3), NOW(3)) RETURNING id`,
        [email],
      ).catch(async () => {
        /* MySQL has no RETURNING; insert then read back. */
        await dataSource.query(
          `INSERT INTO users (id, email, passwordHash, name, emailVerifiedAt, createdAt, updatedAt)
           VALUES (UUID(), ?, 'x', 'Dunning Owner', NOW(3), NOW(3), NOW(3))`,
          [email],
        );

        return dataSource.query(`SELECT id FROM users WHERE email = ?`, [email]);
      });

      await dataSource.query(
        `INSERT INTO tenant_members (id, tenantId, userId, role, createdAt, updatedAt)
         VALUES (UUID(), ?, ?, 'owner', NOW(3), NOW(3))`,
        [tenant.id, user.id],
      );

      return { tenantId: tenant.id, email };
    }

    it('mails the owner when a payment fails', async () => {
      const { tenantId, email } = await tenantWithOwner('first-failure');
      const providerSubscriptionId = `sub_${run}_${seq}_dun`;

      const plan = await dataSource.getRepository(Plan).findOneOrFail({ where: { code: 'free' } });
      const subscriptions = dataSource.getRepository(Subscription);

      await subscriptions.save(
        subscriptions.create({
          tenantId,
          planId: plan.id,
          provider: 'stripe',
          providerSubscriptionId,
          status: SubscriptionStatus.ACTIVE,
        }),
      );

      const { body, signature } = signedEvent({
        type: 'invoice.payment_failed',
        data: {
          object: {
            id: `in_e2e_${run}_${seq}_failed`,
            object: 'invoice',
            status: 'open',
            parent: { subscription_details: { subscription: providerSubscriptionId } },
          },
        },
      });

      expect((await post(body, signature)).status).toBe(200);

      const rows = await dataSource.query(
        `SELECT template, status FROM email_deliveries WHERE recipient = ?`,
        [email],
      );

      expect(rows).toHaveLength(1);
      expect(rows[0].template).toBe('billing-payment-failed');
    });

    /**
     * 🔴 **One lapse, one email.** Stripe's dunning fires several times per
     * lapse and `MailService` has no dedupe — `graceEndsAt` is what makes four
     * identical warnings impossible, and only the database can show that.
     */
    it('sends one email however many failures arrive in a lapse', async () => {
      const { tenantId, email } = await tenantWithOwner('repeat-failure');
      const providerSubscriptionId = `sub_${run}_${seq}_rep`;

      const plan = await dataSource.getRepository(Plan).findOneOrFail({ where: { code: 'free' } });
      const subscriptions = dataSource.getRepository(Subscription);

      await subscriptions.save(
        subscriptions.create({
          tenantId,
          planId: plan.id,
          provider: 'stripe',
          providerSubscriptionId,
          status: SubscriptionStatus.ACTIVE,
        }),
      );

      for (let attempt = 0; attempt < 3; attempt += 1) {
        const { body, signature } = signedEvent({
          type: 'invoice.payment_failed',
          data: {
            object: {
              id: `in_e2e_${run}_${seq}_rep${attempt}`,
              object: 'invoice',
              status: 'open',
              parent: { subscription_details: { subscription: providerSubscriptionId } },
            },
          },
        });

        expect((await post(body, signature)).status).toBe(200);
      }

      const [{ count }] = await dataSource.query(
        `SELECT COUNT(*) AS count FROM email_deliveries WHERE recipient = ?`,
        [email],
      );

      expect(Number(count)).toBe(1);
    });
  });
  /**
   * X1 — the billing period, proven to reach the database.
   *
   * 🔴 **`currentPeriodEnd` was ALWAYS null in production.** The lifecycle read
   * `current_period_end` from the subscription, where this API version does not
   * put it — it lives on `items.data[0]`. Every layer agreed with the mistake:
   * the unit fixture supplied the defunct field, and `billing-account.e2e` sets
   * the column by hand rather than earning it through a webhook.
   *
   * ⚠️ **Nothing above this suite could have caught it.** The contract spec
   * proves the shape against the library's types; only this proves the value
   * survives a real signature, a real handler and a real MySQL column — which
   * is what the merchant's screen actually depends on.
   */
  describe('the billing period reaches the database (X1)', () => {
    it('stores the period end from the item, clearing the settling notice', async () => {
      const plan = await dataSource.getRepository(Plan).findOneOrFail({ where: { code: 'free' } });

      seq += 1;
      const providerCustomerId = `cus_${run}_${seq}`;
      const providerSubscriptionId = `sub_${run}_${seq}_period`;

      const tenant = await dataSource.getRepository(Tenant).save(
        dataSource.getRepository(Tenant).create({
          name: `Period ${run}-${seq}`,
          slug: `whook-${run}-${seq}`,
          planId: plan.id,
          billingCurrency: 'EUR',
        }),
      );

      const subscriptions = dataSource.getRepository(Subscription);

      /*
       * 📌 **Seeded exactly as a just-paid merchant is**: linked to a provider
       * subscription, with no billing period yet. That is F112's `settling`
       * state — the one that showed "Confirming your payment…" for ever.
       */
      const subscription = await subscriptions.save(
        subscriptions.create({
          tenantId: tenant.id,
          planId: plan.id,
          provider: 'stripe',
          providerCustomerId,
          providerSubscriptionId,
          status: SubscriptionStatus.TRIALING,
          currentPeriodEnd: null,
        }),
      );

      /* 2026-12-01T00:00:00Z, as Stripe sends it: epoch SECONDS. */
      const periodEnd = 1_796_083_200;

      const { body, signature } = signedEvent({
        type: 'customer.subscription.updated',
        data: {
          object: {
            id: providerSubscriptionId,
            object: 'subscription',
            status: 'active',
            customer: providerCustomerId,
            cancel_at: null,
            /* 🔴 On the ITEM. A payload with the field on the subscription is
             * one this API version never sends, and the old code only read. */
            items: {
              object: 'list',
              data: [{ id: `si_${run}_${seq}`, current_period_end: periodEnd }],
            },
          },
        },
      });

      expect((await post(body, signature)).status).toBe(200);

      const updated = await subscriptions.findOneByOrFail({ id: subscription.id });

      expect(updated.status).toBe(SubscriptionStatus.ACTIVE);

      /* 🔴 The value, through the column, not merely non-null. */
      expect(updated.currentPeriodEnd).not.toBeNull();
      expect(updated.currentPeriodEnd?.toISOString()).toBe('2026-12-01T00:00:00.000Z');

      /*
       * 🔴 **The merchant-visible consequence.** F112 computes `settling` from
       * exactly these three columns; with the period stored, the notice clears.
       */
      const settling =
        updated.provider !== 'none' &&
        updated.providerSubscriptionId !== null &&
        updated.currentPeriodEnd === null;

      expect(settling).toBe(false);
    });
  });
  /**
   * M23.4 — the retry worker, against the real table.
   *
   * 🔴 **This is the work STRIPE WILL NOT retry.** Stripe redelivers a non-2xx
   * for days; what nothing covered is a row we answered `200` to and then
   * failed to finish, or a delivery whose process died mid-handler. Both leave
   * `processedAt` null — the state N1's ordering exists to make visible.
   *
   * 📌 **Only the database can prove the query.** `processedAt IS NULL AND
   * deadAt IS NULL AND createdAt < ?` is three conditions over real columns and
   * a real index; a mocked repository returns whatever it was told to.
   */
  describe('the retry worker (M23.4)', () => {
    async function seedUnprocessed(over: {
      type?: string;
      payload?: string;
      attempts?: number;
      deadAt?: string | null;
      ageMs?: number;
    }): Promise<string> {
      seq += 1;

      const eventId = `evt_e2e_${run}_retry_${seq}`;
      const ageMs = over.ageMs ?? 120_000;

      await dataSource.query(
        `INSERT INTO billing_events
           (id, provider, providerEventId, type, payload, processedAt, error, attempts, deadAt, createdAt, updatedAt)
         VALUES (UUID(), 'stripe', ?, ?, ?, NULL, 'first failure', ?, ?,
                 DATE_SUB(NOW(3), INTERVAL ? MICROSECOND), NOW(3))`,
        [
          eventId,
          over.type ?? 'customer.subscription.updated',
          over.payload ?? '{}',
          over.attempts ?? 0,
          over.deadAt ?? null,
          ageMs * 1000,
        ],
      );

      return eventId;
    }

    async function rowOf(eventId: string) {
      const [row] = (await dataSource.query(
        `SELECT processedAt, deadAt, attempts, error FROM billing_events WHERE providerEventId = ?`,
        [eventId],
      )) as { processedAt: Date | null; deadAt: Date | null; attempts: number; error: string | null }[];

      return row;
    }

    /**
     * 🔴 **An unrecognised event type is a NO-OP, not a failure** — which makes
     * it the honest way to prove the happy path here: the worker picks the row
     * up, the handler declines it, and the row settles.
     */
    it('settles an unprocessed row it can handle', async () => {
      const eventId = await seedUnprocessed({ type: 'customer.discount.created' });

      const worker = app.get(BillingEventRetryService, { strict: false });
      const outcome = await worker.retryPending();

      expect(outcome.retried).toBeGreaterThan(0);

      const row = await rowOf(eventId);

      expect(row.processedAt).not.toBeNull();
      expect(row.error).toBeNull();
      expect(Number(row.attempts)).toBe(1);
    });

    /**
     * 🔴 **A dead row is never retried again.** With `processedAt` null it
     * would otherwise stay in the retryable set for ever, and a handler that
     * fails deterministically would be re-run every cycle until a person
     * noticed.
     */
    it('never picks up a row that was already dead-lettered', async () => {
      const eventId = await seedUnprocessed({
        type: 'customer.discount.created',
        deadAt: '2026-09-01 00:00:00.000',
        attempts: 5,
      });

      const worker = app.get(BillingEventRetryService, { strict: false });

      await worker.retryPending();

      const row = await rowOf(eventId);

      /* Untouched: still unprocessed, still dead, attempts unchanged. */
      expect(row.processedAt).toBeNull();
      expect(row.deadAt).not.toBeNull();
      expect(Number(row.attempts)).toBe(5);
    });

    /**
     * 🔴 **F125: two workers racing must not process one event twice.**
     *
     * This is the claim's entire purpose, and only the database can prove it —
     * `FOR UPDATE SKIP LOCKED` is a MySQL behaviour, and a mocked repository
     * can imitate the call but not the lock. Two passes are started together;
     * between them each row must be handled **exactly once**.
     */
    it('processes each row once when two workers run together', async () => {
      const ids = [
        await seedUnprocessed({ type: 'customer.discount.created' }),
        await seedUnprocessed({ type: 'customer.discount.created' }),
        await seedUnprocessed({ type: 'customer.discount.created' }),
      ];

      const worker = app.get(BillingEventRetryService, { strict: false });

      /* Both passes in flight at once, as two instances would be. */
      const [a, b] = await Promise.all([worker.retryPending(), worker.retryPending()]);

      /*
       * 🔴 **`attempts` is the witness.** It is stamped once per claim, so a
       * row claimed by both passes would show 2. Exactly one attempt each is
       * what SKIP LOCKED buys.
       */
      for (const eventId of ids) {
        const row = await rowOf(eventId);

        expect(row.processedAt).not.toBeNull();
        expect(Number(row.attempts)).toBe(1);
      }

      /* ⚠️ And no row was counted twice across the two passes. */
      expect(a.retried + b.retried).toBeGreaterThanOrEqual(3);
    });

    /**
     * ⚠️ **A row whose request may still be running is left alone.** The row is
     * written before the work, so a webhook in flight has `processedAt` null —
     * retrying it would run the same event concurrently with itself.
     */
    it('leaves a freshly written row for its own request to finish', async () => {
      const eventId = await seedUnprocessed({
        type: 'customer.discount.created',
        ageMs: 1_000,
      });

      const worker = app.get(BillingEventRetryService, { strict: false });

      await worker.retryPending();

      const row = await rowOf(eventId);

      expect(row.processedAt).toBeNull();
      expect(Number(row.attempts)).toBe(0);
    });
  });
  /**
   * Phase 24's exit criteria, walked as one merchant (F135).
   *
   * 🔴 **Phase 24 was ticked with this untested, and the tick was wrong.** Its
   * exit asks for *"the full lapse lifecycle tested end-to-end"* and *"no
   * scenario in which a paid, then lapsed, then recovered merchant loses
   * configuration"*. Coverage existed per stage and **nothing followed one
   * merchant through** — so the phase's strongest promise, that configuration
   * survives a lapse, was asserted nowhere.
   *
   * 📌 **The closest existing test asserts the BILLING FLAG only**: that a
   * recovered subscription is `ACTIVE` with `graceEndsAt` null. It never looks
   * at an option set. A merchant does not care whether a column cleared; they
   * care whether their work is still there.
   */
  describe('the full lapse lifecycle (Phase 24 exit)', () => {
    it('keeps a merchant’s configuration through fail, lapse and recovery', async () => {
      const plan = await dataSource.getRepository(Plan).findOneOrFail({ where: { code: 'free' } });

      seq += 1;
      const providerSubscriptionId = `sub_${run}_${seq}_lifecycle`;

      const tenant = await dataSource.getRepository(Tenant).save(
        dataSource.getRepository(Tenant).create({
          name: `Lifecycle ${run}-${seq}`,
          slug: `whook-${run}-${seq}`,
          planId: plan.id,
          billingCurrency: 'EUR',
        }),
      );

      const subscriptions = dataSource.getRepository(Subscription);
      const subscription = await subscriptions.save(
        subscriptions.create({
          tenantId: tenant.id,
          planId: plan.id,
          provider: 'stripe',
          providerCustomerId: `cus_${run}_${seq}`,
          providerSubscriptionId,
          status: SubscriptionStatus.ACTIVE,
        }),
      );

      /*
       * The merchant's work: a store and a published option set. This is what
       * the criterion is about — everything below asserts it is still here.
       */
      const [store] = (await dataSource.query('SELECT UUID() AS id')) as { id: string }[];

      await dataSource.query(
        `INSERT INTO stores (id, tenantId, platform, name, storeUrl, status, configVersion,
                             createdAt, updatedAt)
         VALUES (?, ?, 'woocommerce', 'Lifecycle', ?, 'connected', 1, NOW(3), NOW(3))`,
        [store.id, tenant.id, `https://lifecycle-${run}-${seq}.example.com`],
      );

      const [set] = (await dataSource.query('SELECT UUID() AS id')) as { id: string }[];

      await dataSource.query(
        `INSERT INTO option_sets (id, tenantId, storeId, name, status, createdAt, updatedAt)
         VALUES (?, ?, ?, 'Engraving', 'published', NOW(3), NOW(3))`,
        [set.id, tenant.id, store.id],
      );

      const survives = async (): Promise<{ sets: number; stores: number }> => {
        const [row] = (await dataSource.query(
          /* ⚠️ `sets` is a MySQL reserved word; the aliases are quoted names. */
          `SELECT
             (SELECT COUNT(*) FROM option_sets
               WHERE tenantId = ? AND deletedAt = '1970-01-01 00:00:00.000') AS setCount,
             (SELECT COUNT(*) FROM stores WHERE tenantId = ?) AS storeCount`,
          [tenant.id, tenant.id],
        )) as { setCount: number; storeCount: number }[];

        return { sets: Number(row.setCount), stores: Number(row.storeCount) };
      };

      expect(await survives()).toEqual({ sets: 1, stores: 1 });

      /* ── Stage 1: the payment fails, and a 14-day clock starts. ── */
      const failed = signedEvent({
        type: 'invoice.payment_failed',
        data: {
          object: {
            id: `in_e2e_${run}_${seq}_fail`,
            object: 'invoice',
            status: 'open',
            parent: { subscription_details: { subscription: providerSubscriptionId } },
          },
        },
      });

      expect((await post(failed.body, failed.signature)).status).toBe(200);

      const lapsing = await subscriptions.findOneByOrFail({ id: subscription.id });

      expect(lapsing.status).toBe(SubscriptionStatus.PAST_DUE);
      expect(lapsing.graceEndsAt).not.toBeNull();

      /* 🔴 Nothing is deleted when a payment fails. */
      expect(await survives()).toEqual({ sets: 1, stores: 1 });

      /* ── Stage 2: the grace period expires. ── */
      await dataSource.query(
        `UPDATE subscriptions SET graceEndsAt = DATE_SUB(NOW(3), INTERVAL 1 DAY) WHERE id = ?`,
        [subscription.id],
      );

      /*
       * 🔴 **The storefront still serves, which is ADR-116's whole point.**
       * Asserted through the document builder rather than a flag: this is the
       * path a customer's browser reaches, and it must not consult billing.
       */
      const documents = app.get(ConfigDocumentBuilder, { strict: false });
      const lapsed = await documents.build(store.id);

      expect(lapsed.plan.read_only).toBe(true);

      /* 🔴 The store still has a servable document — the shop is not dark. */
      expect(lapsed.config_version).toBe(1);
      expect(lapsed.store_id).toBe(store.id);
      expect(await survives()).toEqual({ sets: 1, stores: 1 });

      /* ── Stage 3: the merchant pays. ── */
      const paid = signedEvent({
        type: 'invoice.paid',
        data: {
          object: {
            id: `in_e2e_${run}_${seq}_paid`,
            object: 'invoice',
            status: 'paid',
            currency: 'eur',
            subtotal: 2900,
            total_taxes: [{ amount: 609 }],
            total: 3509,
            created: 1_755_216_000,
            status_transitions: { paid_at: 1_755_216_060 },
            customer_address: { country: 'de' },
            parent: { subscription_details: { subscription: providerSubscriptionId } },
          },
        },
      });

      expect((await post(paid.body, paid.signature)).status).toBe(200);

      const recovered = await subscriptions.findOneByOrFail({ id: subscription.id });

      expect(recovered.status).toBe(SubscriptionStatus.ACTIVE);
      expect(recovered.graceEndsAt).toBeNull();

      /*
       * 🔴 **The criterion itself**: paid → lapsed → recovered, and the
       * merchant's configuration is exactly as they left it.
       */
      expect(await survives()).toEqual({ sets: 1, stores: 1 });

      const restored = await documents.build(store.id);

      /*
       * 🔴 **The plan state recovers with the subscription.** The rendered
       * `option_sets` array is deliberately NOT asserted here: a document lists
       * a set only when a matching `option_set_versions` snapshot exists, which
       * is publishing's contract and is proven in `publish.e2e-spec`. What this
       * criterion is about — *did the merchant lose configuration* — is the row
       * count above, checked at all three stages.
       */
      expect(restored.plan.read_only).toBe(false);
      expect(restored.plan.grace_ends_at).toBeNull();
    });
  });
});
